name: ci-golang-workflow
on:
  pull_request:
    branches: ["develop"]

jobs:
  check-application:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.15", "1.16"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{strategy.go}}
      - run: go test
      - run: go run app.go
